version: '3.1'

services:

  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports: 
    - 12345:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080