apiVersion: v1
kind: Secret
metadata:
  name: http-api-server-secret
  namespace: http-api-server
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
  POSTGRES_PASSWORD: YWRtaW4xMjM=
